lab db "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    db "    x   xxxxxx                               x       x     x"
    db "x x x x x    x xxxxxxxxxxxxxxxxxxxxxxxxxxx x xxxxxxx x xxx x"
    db "x x x x x xx x       x            x      x x           x   x"
    db "x x       xx xxxxxxx x xxxxxxxx x x xxxx x xxxxxxxxxxxxxxxxx"
    db "x xxxxxxxxxx xxxxxxx x x        x x    x x     x           x"
    db "x     xxxxxx xxx     x xxxxxxxxxx xxxxxx x xxx xxxxxx xxxx x"
    db "xxxxx x      xxx xxxxx x                 x x x        x    x"
    db "x     x xxxxxxxx x     x xxxxxxxxxxxxxxx x x xxxxx xxxxxxx x"
    db "x xxxxx xxxxxxxx x xxxxx x               x x               x"
    db "x     x          x x     x xxxxxxxxxxxxx x xxxxxxxxxxxxxxxxx"
    db "xxxxx xxxxxxxxxxxx x xxxxx x          x xx   x     xxx     x"
    db "x                  x       xxxxxxxxxx x xx x x xxx     xxx x"
    db "x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx x x xxxxxxxxxxx x"
    db "x xxxxx                                    x               x"
    db "x x   x xx xxxxx xxx x xx xxxxxxxxxxxxxx x xxxxxxx xxxxxxx x"
    db "x x x x x  x x x  xx x  x xxx            x       x  x      x"
    db "x x x x xx x x xx    xx x xxx xx xxxxxxxxxxxxxxxxxx  xxxx xx"
    db "x x x x x  x   xx x xxxxx   x xx x                xx x    xx"
    db "x x x x x xx xx   x     xxx x  x x xxxxxxxxxxxxxx x  xxxx  x"
    db "x x x x x    x  xxx       x xx x x x            x xxxxxxxxxx"
    db "x x x x xxxxxxxxxxxxxxxxxxx xx x x x xxxxxxxxxxxx          x"
    db "x                         x x  x x x            x xxxxxxxx x"
    db "x xxx x x xxxxxx xxx xxxx x xxxx x xxxxxxxxxxxx x x   x  x x"
    db "x  x  x x x   xx x   x  x x      x x            x x x   xx x"
    db "x     x x xxx    xx    xx xxxxxxxx x xxxxxxxxxxxx x xxxxxx x"
    db "xxxxxxx x     xx x  xx xx          x            x x        x"
    db "x       xxxxxxxx xxxxx x   x   x   xxxxxxxxxxxx x x xxxxxxxx"
    db "x xxxxxxx      x     x   x   x   x              x x        x"
    db "x x   x x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxx x"
    db "x   x     x                                       x      x x"
    db "xxxxxxxxxxx xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxx x"
    db "x       x       x     x             x                      x"
    db "x xx xxxxxxxxxxxx xxx x xxxxxxxxxxx x xxxxxxxxxxxxxxxxxxxxxx"
    db "x x               x   x x         x x    x          x      x"
    db "x x xxxxxx xxxxxxxxxxxx x xxxxxxxxx xxxx xxxx xxxxx xxx xx x"
    db "x x      x       x      x         x x         x         x  x"
    db "x xxxxxx xxxxxxxxx xxxxxxxxxxxxxx x xxxxxxxxxxxxxxxxxxxxxxxx"
    db "x      x                          x                         "
    db "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    
    
;Solucion
;lab db "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
;db ">>>>x   xxxxxx>>>>>>>>>>>>>>>>>>>>>>>>>>>>v  x       x     x"
;db "x xvx x x^>>>x^xxxxxxxxxxxxxxxxxxxxxxxxxxxvx xxxxxxx x xxx x"
;db "x xvx x x^xxvx^<<<<<<x            x      xvx           x   x"
;db "x xv>>>>>^xxvxxxxxxx^x xxxxxxxx x x xxxx xvxxxxxxxxxxxxxxxxx"
;db "x xxxxxxxxxxvxxxxxxx^x x        x x    x xv    x           x"
;db "x     xxxxxxvxxx>>>>^x xxxxxxxxxx xxxxxx xvxxx xxxxxx xxxx x"
;db "xxxxx xv<<<<<xxx^xxxxx x                 xvx x        x    x"
;db "x     xvxxxxxxxx^x     x xxxxxxxxxxxxxxx xvx xxxxx xxxxxxx x"
;db "x xxxxxvxxxxxxxx^x xxxxx x               xvx               x"
;db "x     x>>>>>>>>>^x x     x xxxxxxxxxxxxx xvxxxxxxxxxxxxxxxxx"
;db "xxxxx xxxxxxxxxxxx x xxxxx x          x xxv  x     xxx     x"
;db "x                  x       xxxxxxxxxx x xxvx x xxx     xxx x"
;db "x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvx x xxxxxxxxxxx x"
;db "x xxxxx<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<x               x"
;db "x x   xvxx xxxxx xxx x xx xxxxxxxxxxxxxx x xxxxxxx xxxxxxx x"
;db "x x x xvx  x x x  xx x  x xxx            x       x  x      x"
;db "x x x xvxx x x xx    xx x xxx xx xxxxxxxxxxxxxxxxxx  xxxx xx"
;db "x x x xvx  x   xx x xxxxx   x xx x>>>>>>>>>>>>>>>>xx x    xx"
;db "x x x xvx xx xx   x     xxx x  x x^xxxxxxxxxxxxxxvx  xxxx  x"
;db "x x x xvx    x  xxx       x xx x x^x            xvxxxxxxxxxx"
;db "x x x xvxxxxxxxxxxxxxxxxxxx xx x x^x xxxxxxxxxxxxv         x"
;db "x      >>>>>>>>>>>>>>>>>>vx x  x x^x            xvxxxxxxxx x"
;db "x xxx x x xxxxxx xxx xxxxvx xxxx x^xxxxxxxxxxxx xvx   x  x x"
;db "x  x  x x x   xx x   x  xvx      x^x            xvx x   xx x"
;db "x     x x xxx    xx    xxvxxxxxxxx^x xxxxxxxxxxxxvx xxxxxx x"
;db "xxxxxxx x     xx x  xx xx>>>>>>>>>^x            xvx        x"
;db "x       xxxxxxxx xxxxx x   x   x   xxxxxxxxxxxx xvx xxxxxxxx"
;db "x xxxxxxx      x     x   x   x   x              xvx        x"
;db "x x   x x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxx x"
;db "x   x     x      v<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<x      x x"
;db "xxxxxxxxxxx xxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxx x"
;db "x       x       xv    x>>>>>>>>>>>>vx                      x"
;db "x xx xxxxxxxxxxxxvxxx x^xxxxxxxxxxxvx xxxxxxxxxxxxxxxxxxxxxx"
;db "x xv<<<<<<<<<<<<<<x   x^x         xvx    x          x      x"
;db "x xvxxxxxx xxxxxxxxxxxx^x xxxxxxxxxvxxxx xxxx xxxxx xxx xx x"
;db "x x>>>>>vx       x>>>>>>x         xvx         x         x  x"
;db "x xxxxxxvxxxxxxxxx^xxxxxxxxxxxxxx xvxxxxxxxxxxxxxxxxxxxxxxxx"
;db "x      xv>>>>>>>>>^               x>>>>>>>>>>>>>>>>>>>>>>>>>"
;db "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"